steps:
  - name: 'maven:3.9-eclipse-temurin-17'
    id: 'Run Java unit tests'
    dir: 'gcp-java-ci-cd-demo'
    entrypoint: 'mvn'
    args: ['test']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    dir: 'gcp-java-ci-cd-demo'
    args:
      - 'build'
      - '-t'
      - 'australia-southeast1-docker.pkg.dev/gcp-cicd-assignment/cicd-demo-repo/gcp-java-ci-cd-demo:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image'
    args:
      - 'push'
      - 'australia-southeast1-docker.pkg.dev/gcp-cicd-assignment/cicd-demo-repo/gcp-java-ci-cd-demo:$SHORT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'gcp-java-ci-cd-demo'
      - '--image'
      - 'australia-southeast1-docker.pkg.dev/gcp-cicd-assignment/cicd-demo-repo/gcp-java-ci-cd-demo:$SHORT_SHA'
      - '--region'
      - 'australia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'australia-southeast1-docker.pkg.dev/gcp-cicd-assignment/cicd-demo-repo/gcp-java-ci-cd-demo:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY